workflows:
    deploy-to-appstore: 
      name: Deploy to App Store Connect
      integrations: 
        app_store_connect: Codemagic API Key
      environment:
        groups:
          - code-signing
        vars:
          XCODE_WORKSPACE: "Runner.xcworkspace" # <-- Put the name of your workspace here.
          XCODE_SCHEME: "Runner" # <-- Put the name of your scheme here.
          BUNDLE_ID: "io.codemagic.annaFlutterDemo" # <-- Put your Bundle Id here.
        xcode: 16.4
      scripts:
        - name: Set up keychain to be used for code signing using Codemagic CLI 'keychain' command
          script: keychain initialize
        - name: Fetch signing files
          script: | 
            app-store-connect fetch-signing-files "$BUNDLE_ID" \
              --platform IOS \
              --type IOS_APP_DEVELOPMENT \
              --create
        - name: Set up signing certificate
          script: keychain add-certificates
        - name: Set up code signing settings on Xcode project
          script: xcode-project use-profiles \
                    --custom-export-options='{"testFlightInternalTestingOnly":true}'
        - name: Increment build number
          script: |
            agvtool new-version -all $(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_APPLE_ID") + 1))
        - name: Get Flutter packages
          script: | 
            flutter pub get
        - name: Install pods
          script: | 
            find . -name "Podfile" -execdir pod install \;
        - name: Flutter build ipa
          script: | 
            flutter build ipa --release \
            --build-name=1.0.0 \
            --export-options-plist=/Users/builder/export_options.plist
      artifacts:
        - build/ios/ipa/*.ipa
